-- Generated by scripts/build_supabase_setup.py. Run in Supabase SQL Editor.
-- Installs profiles, private inspection history and RLS in one transaction.
begin;

-- 001_initial_schema.sql
-- ComplyVision initial Supabase schema
-- Run this migration in the Supabase SQL Editor or via Supabase CLI.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'inspector'
    check (role in ('inspector', 'reviewer', 'admin')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inspections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null check (status in ('PASS', 'FAIL', 'REVIEW', 'NOT_APPLICABLE')),
  product_name text,
  source_filename text,
  report jsonb not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists inspections_user_id_created_at_idx
  on public.inspections (user_id, created_at desc);

create index if not exists inspections_status_idx
  on public.inspections (status);

-- Keep updated_at current for profile edits.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

-- Create a profile automatically for every new Auth user.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Enable RLS on every exposed application table.
alter table public.profiles enable row level security;
alter table public.inspections enable row level security;

-- Least-privilege Data API grants.
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.inspections from anon, authenticated;

grant select on table public.profiles to authenticated;
grant update (full_name) on table public.profiles to authenticated;
grant select, insert on table public.inspections to authenticated;

-- Profiles: users can read and update only their own profile.
drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id and coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false');

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id and coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false')
with check ((select auth.uid()) = id and coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false');

-- Inspections: confirmed accounts can read/insert only their own immutable history.
drop policy if exists "Users can read their own inspections" on public.inspections;
create policy "Users can read their own inspections"
on public.inspections
for select
to authenticated
using ((select auth.uid()) = user_id and coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false');

drop policy if exists "Users can create their own inspections" on public.inspections;
create policy "Users can create their own inspections"
on public.inspections
for insert
to authenticated
with check ((select auth.uid()) = user_id and coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false');

-- Explicitly remove legacy edit/delete policies when upgrading an earlier draft.
drop policy if exists "Users can update their own inspections" on public.inspections;
drop policy if exists "Users can delete their own inspections" on public.inspections;

-- 002_inspection_source_preview.sql
-- Store a compact source-image preview for human-friendly inspection history.
-- The original uploaded image is not stored in the report JSON; this preview is intentionally resized client-side.
alter table public.inspections
  add column if not exists source_image_data_url text;

-- 003_inspector_profile_details.sql
-- Extended inspector profile information.
-- Email remains managed by Supabase Auth and is intentionally not stored as an editable profile field.

alter table public.profiles
  add column if not exists age integer,
  add column if not exists designation text,
  add column if not exists employee_id text,
  add column if not exists department text,
  add column if not exists qualification text,
  add column if not exists experience_years integer,
  add column if not exists office_location text,
  add column if not exists address text,
  add column if not exists bio text;

alter table public.profiles
  drop constraint if exists profiles_age_check;

alter table public.profiles
  add constraint profiles_age_check
  check (age is null or age between 18 and 100);

alter table public.profiles
  drop constraint if exists profiles_experience_years_check;

alter table public.profiles
  add constraint profiles_experience_years_check
  check (experience_years is null or experience_years between 0 and 80);

-- 004_protect_profile_role.sql
-- Profile ownership must not allow users to promote themselves.
revoke update on table public.profiles from authenticated;
grant update (full_name, age, designation, employee_id, department,
  qualification, experience_years, office_location, address, bio)
  on public.profiles to authenticated;

-- 005_verified_user_persistence.sql
alter table public.inspections drop constraint if exists inspections_report_status_matches;
drop policy if exists "Verified accounts only" on public.inspections;
drop policy if exists "Verified profiles only" on public.profiles;
-- Apply after 001-004. Enable the deployment database switch only after RLS checks.
alter table public.inspections drop constraint if exists inspections_status_check;
alter table public.inspections add constraint inspections_status_check
  check (status in ('PASS', 'FAIL', 'REVIEW', 'NOT_APPLICABLE'));
-- Newly written records must faithfully index their canonical outcome.
-- NOT VALID avoids rewriting/rejecting existing data; new writes are still checked.
alter table public.inspections add constraint inspections_report_status_matches
  check (report #>> '{summary,overall_status}' is not null
    and status = report #>> '{summary,overall_status}') not valid;

-- Anonymous Auth sessions also use the authenticated database role. Deny them explicitly.
create policy "Verified accounts only" on public.inspections as restrictive
  for all to authenticated
  using (coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false')
  with check (coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false');
create policy "Verified profiles only" on public.profiles as restrictive
  for all to authenticated
  using (coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false')
  with check (coalesce((select auth.jwt() ->> 'is_anonymous'), 'true') = 'false');

-- Reports are immutable in this release. Ownership and original outcomes cannot be edited.
revoke update, delete on public.inspections from authenticated;
drop policy if exists "Users can update their own inspections" on public.inspections;
drop policy if exists "Users can delete their own inspections" on public.inspections;
-- 004 already restricts profile updates to non-privileged columns; preserve that grant.
revoke all on function public.handle_new_user() from public, anon, authenticated;
insert into public.profiles (id, full_name)
  select id, coalesce(raw_user_meta_data ->> 'full_name', '') from auth.users
  on conflict (id) do nothing;

-- 006_bound_source_previews.sql
alter table public.inspections drop constraint if exists inspections_source_preview_bounded;
-- Existing records remain available for audit; validate old rows separately before VALIDATE CONSTRAINT.
alter table public.inspections add constraint inspections_source_preview_bounded
  check (source_image_data_url is null or
    (octet_length(source_image_data_url) <= 2097152 and source_image_data_url ~ '^data:image/jpeg;base64,[A-Za-z0-9+/]+={0,2}$')) not valid;

commit;
