"""Build a rerunnable SQL Editor setup script from the versioned migrations."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parts = ["-- Generated by scripts/build_supabase_setup.py. Run in Supabase SQL Editor.\n-- Installs profiles, private inspection history and RLS in one transaction.\nbegin;\n"]
for migration in sorted((root / "supabase/migrations").glob("*.sql")):
    text = migration.read_text()
    text = "\n".join(line for line in text.splitlines() if line.strip().lower() not in {"begin;", "commit;"})
    if migration.name.startswith("005_"):
        text = '''alter table public.inspections drop constraint if exists inspections_report_status_matches;
drop policy if exists "Verified accounts only" on public.inspections;
drop policy if exists "Verified profiles only" on public.profiles;
''' + text
    if migration.name.startswith("006_"):
        text = "alter table public.inspections drop constraint if exists inspections_source_preview_bounded;\n" + text
    parts.append(f"\n-- {migration.name}\n{text}\n")
parts.append("\ncommit;\n")
(root / "supabase/setup.sql").write_text("".join(parts))
