import type { CanonicalReport, JsonValue } from "@/types/report";

function display(value: JsonValue | undefined): string {
  if (value === null || value === undefined || value === "") return "Unknown";
  if (Array.isArray(value)) return value.map(display).join(", ");
  if (typeof value === "object") return Object.entries(value).filter(([, item]) => item !== null).map(([key, item]) => `${humanize(key)}: ${display(item)}`).join("; ") || "Unknown";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  return String(value);
}

function humanize(value: string): string {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function inline(value: string): string {
  return value.replaceAll("|", "\\|").replace(/\s*\n\s*/g, " ").trim() || "Unknown";
}

function status(value: string): string {
  return value === "NOT_APPLICABLE" ? "N/A" : value;
}

function percent(value: number | null | undefined): string {
  return typeof value === "number" ? `${(value * 100).toFixed(1)}%` : "Unknown";
}

function formatDate(value: string | null | undefined): string {
  if (!value) return "Unknown";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(date);
}

export function reportToJson(report: CanonicalReport): string {
  return `${JSON.stringify(report, null, 2)}\n`;
}

export function reportToMarkdown(report: CanonicalReport): string {
  const processed = formatDate(report.image.processing_timestamp);
  const lines = [
    "# Package Compliance Report",
    "",
    "*Generated by ComplyVision*",
    "",
    "## Inspection overview",
    "",
    "| Detail | Value |",
    "| --- | --- |",
    `| Overall outcome | **${status(report.summary.overall_status)}** |`,
    `| Source image | ${inline(report.image.filename)} |`,
    `| Image dimensions | ${report.image.width ?? "?"} x ${report.image.height ?? "?"} px |`,
    `| Processed | ${inline(processed)} |`,
    `| Report schema | ${inline(report.report_version)} |`,
    "",
    report.summary.reason,
    "",
    "## Compliance summary",
    "",
    "| Pass | Fail | Review | N/A |",
    "| ---: | ---: | ---: | ---: |",
    `| ${report.summary.pass_count} | ${report.summary.fail_count} | ${report.summary.review_count} | ${report.summary.not_applicable_count} |`,
    "",
    `PASS ${report.summary.pass_count} · FAIL ${report.summary.fail_count} · REVIEW ${report.summary.review_count} · NOT_APPLICABLE ${report.summary.not_applicable_count}`,
    "",
    "## Extracted declarations",
    "",
    "| Declaration | Status | Value | Confidence |",
    "| --- | --- | --- | ---: |",
  ];

  const fields = Object.values(report.extracted_fields);
  if (fields.length === 0) {
    lines.push("| No declarations returned | - | - | - |");
  } else {
    fields.forEach((field) => lines.push(
      `| ${inline(humanize(field.field_name))} | ${field.present ? "Detected" : "Not detected"} | ${inline(display(field.normalized_value))} | ${percent(field.extraction_confidence)} |`,
    ));
  }

  lines.push("", "## Compliance checks", "");
  if (report.rule_results.length === 0) {
    lines.push("No compliance checks were returned.", "");
  } else {
    report.rule_results.forEach((rule) => {
      lines.push(
        `### ${rule.rule_id} — ${status(rule.status)}`,
        "",
        `**${rule.description}**`,
        "",
        `- Legal source: ${rule.legal_source || "Unknown"}`,
        `- Applicable: ${rule.applicable ? "Yes" : "No"}`,
        `- Evaluation: ${rule.reason || "No additional explanation was provided."}`,
        `- Reason codes: ${rule.reason_codes.join(", ") || "None"}`,
        `- Confidence: ${percent(rule.confidence)}`,
      );
      if (rule.issues?.length) lines.push(`- Issues: ${rule.issues.join(", ")}`);
      lines.push("");
    });
  }

  if (report.warnings.length > 0) {
    lines.push("## Processing notes", "");
    report.warnings.forEach((warning) => lines.push(`- **${warning.code}:** ${warning.message}`));
    lines.push("");
  }

  lines.push(
    "## Image quality",
    "",
    `- Usable: ${report.quality.usable === undefined || report.quality.usable === null ? "Unknown" : report.quality.usable ? "Yes" : "No"}`,
    `- Quality status: ${report.image.quality_status ?? "Unknown"}`,
    `- Blur score: ${report.quality.blur_score ?? "Unknown"}`,
    `- Brightness: ${report.quality.brightness ?? "Unknown"}`,
    `- Glare ratio: ${report.quality.glare_ratio ?? "Unknown"}`,
    `- OCR regions retained: ${report.ocr.filtered_item_count ?? "Unknown"}`,
    "",
    "## Inspector interpretation",
    "",
    `> ${report.disclaimer.replace(/\n/g, "\n> ")}`,
    "",
    "This report is evidence-backed decision support. A REVIEW outcome means the displayed information requires human verification before a final compliance decision is made.",
    "",
    "---",
    "",
    "Generated by ComplyVision.",
    "",
  );
  return lines.join("\n");
}

export function downloadReport(report: CanonicalReport, format: "md"): void {
  const content = reportToMarkdown(report);
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${report.image.filename.replace(/\.[^.]+$/, "") || "package"}-report.${format}`;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}
